generate:
  - types
  - server
accessModifier: public
filter:
  paths:
    - /health
    - /metrics
    - /auth/token
    - /certificates
    - /certificates/renew
    - /routes
    - /routes/{routeId}
