openapi: 3.1.0
info:
  title: PatchBay Service API
  version: 1.0.0
  description: |
    Kept in sync with curated spec at Packages/FountainSpecCuration/openapi/v1/patchbay.yml.
servers:
  - url: http://localhost:7090
tags:
  - name: Canvas
  - name: Instruments
  - name: Links
  - name: Discovery
  - name: Suggest
  - name: Export
  - name: Import
  - name: Store
  - name: Corpus
  - name: Admin
paths:
  /health:
    get:
      operationId: getHealth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, enum: [ok] }
  /canvas:
    get:
      operationId: getCanvas
      responses:
        '200': { description: Canvas, content: { application/json: { schema: { $ref: '#/components/schemas/CanvasState' } } } }
    patch:
      operationId: patchCanvas
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/CanvasPatch' } } }
      responses:
        '200': { description: Updated, content: { application/json: { schema: { $ref: '#/components/schemas/CanvasState' } } } }
  /canvas/zoom/fit:
    post:
      operationId: zoomFit
      responses: { '204': { description: Fitted } }
  /canvas/zoom/actual:
    post:
      operationId: zoomActual
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                viewPoint: { $ref: '#/components/schemas/Point' }
      responses: { '204': { description: Zoom set to 100% } }
  /canvas/zoom:
    post:
      operationId: zoomSet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [scale]
              properties:
                scale: { type: number, minimum: 0.1, maximum: 16 }
                anchorView: { $ref: '#/components/schemas/Point' }
      responses: { '204': { description: Zoom applied } }
  /canvas/pan:
    post:
      operationId: panBy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [dx, dy]
              properties: { dx: { type: number }, dy: { type: number } }
      responses: { '204': { description: Panned } }
  /graph:
    get:
      operationId: getGraph
      responses: { '200': { description: GraphDoc, content: { application/json: { schema: { $ref: '#/components/schemas/GraphDoc' } } } } }
    put:
      operationId: putGraph
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/GraphDoc' } } }
      responses: { '204': { description: Replaced } }
  /instruments:
    get:
      operationId: listInstruments
      responses: { '200': { description: Instruments, content: { application/json: { schema: { type: array, items: { $ref: '#/components/schemas/Instrument' } } } } } }
    post:
      operationId: createInstrument
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/CreateInstrument' } } }
      responses: { '201': { description: Created, content: { application/json: { schema: { $ref: '#/components/schemas/Instrument' } } } } }
  /instruments/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    get:
      operationId: getInstrument
      responses: { '200': { description: Instrument, content: { application/json: { schema: { $ref: '#/components/schemas/Instrument' } } } } }
    patch:
      operationId: patchInstrument
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/PatchInstrument' } } }
      responses: { '200': { description: Updated, content: { application/json: { schema: { $ref: '#/components/schemas/Instrument' } } } } }
    delete:
      operationId: deleteInstrument
      responses: { '204': { description: Deleted } }
  /instruments/{id}/schema:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    get:
      operationId: getInstrumentSchema
      responses: { '200': { description: Property schema, content: { application/json: { schema: { $ref: '#/components/schemas/PropertySchema' } } } } }
  /links:
    get:
      operationId: listLinks
      responses: { '200': { description: Links, content: { application/json: { schema: { type: array, items: { $ref: '#/components/schemas/Link' } } } } } }
    post:
      operationId: createLink
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/CreateLink' } } }
      responses: { '201': { description: Created, content: { application/json: { schema: { $ref: '#/components/schemas/Link' } } } } }
  /links/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    delete:
      operationId: deleteLink
      responses: { '204': { description: Deleted } }
  /ci/endpoints:
    get:
      operationId: listDiscoveredEndpoints
      responses: { '200': { description: Discovered, content: { application/json: { schema: { type: array, items: { $ref: '#/components/schemas/DiscoveredEndpoint' } } } } } }
  /ci/endpoints/{id}/schema:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    get:
      operationId: getDiscoveredEndpointSchema
      responses: { '200': { description: Property schema, content: { application/json: { schema: { $ref: '#/components/schemas/PropertySchema' } } } } }
  /graph/suggest:
    post:
      operationId: suggestLinks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nodeIds: { type: array, items: { type: string } }
                includeUMP: { type: boolean, default: true }
      responses: { '200': { description: Suggestions, content: { application/json: { schema: { type: array, items: { $ref: '#/components/schemas/SuggestedLink' } } } } } }
  /export/json:
    get:
      operationId: exportJSON
      responses: { '200': { description: JSON graph, content: { application/json: { schema: { $ref: '#/components/schemas/GraphDoc' } } } } }
  /export/dsl:
    get:
      operationId: exportDSL
      responses: { '200': { description: DSL text, content: { text/plain: { schema: { type: string } } } } }
  /import/json:
    post:
      operationId: importJSON
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/GraphDoc' } } }
      responses: { '204': { description: Imported } }
  /import/dsl:
    post:
      tags: [Import]
      operationId: importDSL
      requestBody:
        required: true
        content: { text/plain: { schema: { type: string } } }
      responses: { '204': { description: Imported } }
  /store/graphs:
    get:
      tags: [Store]
      operationId: listStoredGraphs
      responses:
        '200': { description: Stored graphs, content: { application/json: { schema: { type: array, items: { $ref: '#/components/schemas/StoredGraph' } } } } }
  /store/graphs/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    get:
      tags: [Store]
      operationId: getStoredGraph
      responses:
        '200': { description: Stored Graph, content: { application/json: { schema: { $ref: '#/components/schemas/StoredGraph' } } } }
    put:
      tags: [Store]
      operationId: putStoredGraph
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/StoredGraph' } } }
      responses: { '204': { description: Upserted } }
  /corpus/snapshot:
    post:
      tags: [Corpus]
      operationId: createCorpusSnapshot
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                includeSchemas: { type: boolean, default: true }
                includeMappings: { type: boolean, default: true }
      responses: { '200': { description: Corpus JSON, content: { application/json: { schema: { $ref: '#/components/schemas/CorpusSnapshot' } } } } }
  /admin/vendor-identity:
    get:
      tags: [Admin]
      operationId: getVendorIdentity
      responses: { '200': { description: Identity, content: { application/json: { schema: { $ref: '#/components/schemas/VendorIdentity' } } } } }
    put:
      tags: [Admin]
      operationId: putVendorIdentity
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/VendorIdentity' } } }
      responses: { '204': { description: Updated } }
  /admin/vendor-identity/allocations:
    get:
      tags: [Admin]
      operationId: listVendorAllocations
      responses: { '200': { description: Allocations, content: { application/json: { schema: { type: array, items: { $ref: '#/components/schemas/Allocation' } } } } } }
    post:
      tags: [Admin]
      operationId: allocateSubId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [instrumentId]
              properties:
                instrumentId: { type: string }
      responses: { '201': { description: Allocation, content: { application/json: { schema: { $ref: '#/components/schemas/Allocation' } } } } }

components:
  schemas:
    Point:
      type: object
      required: [x, y]
      properties: { x: { type: number }, y: { type: number } }
    CanvasTransform:
      type: object
      required: [scale, translation]
      properties:
        scale: { type: number }
        translation: { $ref: '#/components/schemas/Point' }
    CanvasState:
      type: object
      required: [docWidth, docHeight, gridStep, transform]
      properties:
        docWidth: { type: integer }
        docHeight: { type: integer }
        gridStep: { type: integer }
        autoScale: { type: boolean, default: true }
        theme: { type: string, enum: [light, dark], default: light }
        transform: { $ref: '#/components/schemas/CanvasTransform' }
    CanvasPatch:
      type: object
      properties:
        gridStep: { type: integer }
        autoScale: { type: boolean }
        theme: { type: string, enum: [light, dark] }
    InstrumentKind:
      type: string
      enum: [mvk.triangle, mvk.quad, external.coremidi, audiotalk.chat]
    InstrumentIdentity:
      type: object
      properties:
        manufacturer: { type: string }
        product: { type: string }
        displayName: { type: string }
        instanceId: { type: string }
        muid28: { type: integer }
        hasUMPInput: { type: boolean }
        hasUMPOutput: { type: boolean }
    PropertySchema:
      type: object
      required: [version, properties]
      properties:
        version: { type: integer }
        properties:
          type: array
          items:
            type: object
            required: [name, type]
            properties:
              name: { type: string }
              type: { type: string, enum: [float, int, bool, string, enum] }
              min: { type: number }
              max: { type: number }
              step: { type: number }
              default: { oneOf: [ { type: number }, { type: integer }, { type: boolean }, { type: string } ] }
              enumValues: { type: array, items: { type: string } }
              aliases: { type: array, items: { type: string } }
    Instrument:
      type: object
      required: [id, kind, x, y, w, h, identity, propertySchema]
      properties:
        id: { type: string }
        kind: { $ref: '#/components/schemas/InstrumentKind' }
        title: { type: string }
        x: { type: integer }
        y: { type: integer }
        w: { type: integer }
        h: { type: integer }
        identity: { $ref: '#/components/schemas/InstrumentIdentity' }
        propertySchema: { $ref: '#/components/schemas/PropertySchema' }
        propertyDefaults: { type: object, additionalProperties: { oneOf: [ { type: number }, { type: integer }, { type: boolean }, { type: string } ] } }
    CreateInstrument:
      type: object
      required: [id, kind, x, y, w, h]
      properties:
        id: { type: string }
        kind: { $ref: '#/components/schemas/InstrumentKind' }
        title: { type: string }
        x: { type: integer }
        y: { type: integer }
        w: { type: integer }
        h: { type: integer }
        identity: { $ref: '#/components/schemas/InstrumentIdentity' }
    PatchInstrument:
      type: object
      properties:
        title: { type: string }
        x: { type: integer }
        y: { type: integer }
        w: { type: integer }
        h: { type: integer }
        propertyDefaults: { type: object, additionalProperties: { oneOf: [ { type: number }, { type: integer }, { type: boolean }, { type: string } ] } }
    PropertyRef:
      type: string
      description: 'instrumentId.propertyName'
    UMPMessageKind:
      type: string
      enum: [noteOn, noteOff, cc, pitchBend]
    UMPSource:
      type: object
      required: [endpointId, group, channel, message]
      properties:
        endpointId: { type: string }
        group: { type: integer }
        channel: { type: integer }
        message: { $ref: '#/components/schemas/UMPMessageKind' }
        cc: { type: integer }
        note: { type: integer }
    MappingFunction:
      type: object
      properties:
        scale: { type: number, default: 1.0 }
        offset: { type: number, default: 0.0 }
        outMin: { type: number }
        outMax: { type: number }
        smoothing: { type: number }
        curve: { type: string, enum: [linear, exp, log], default: linear }
    PropertyLink:
      type: object
      required: [from, to]
      properties:
        from: { $ref: '#/components/schemas/PropertyRef' }
        to: { $ref: '#/components/schemas/PropertyRef' }
        direction: { type: string, enum: [a_to_b, b_to_a, bidirectional], default: a_to_b }
    UMPMapping:
      type: object
      required: [source, to]
      properties:
        source: { $ref: '#/components/schemas/UMPSource' }
        to: { $ref: '#/components/schemas/PropertyRef' }
        map: { $ref: '#/components/schemas/MappingFunction' }
    Link:
      type: object
      required: [id, kind]
      properties:
        id: { type: string }
        kind: { type: string, enum: [property, ump] }
        property: { $ref: '#/components/schemas/PropertyLink' }
        ump: { $ref: '#/components/schemas/UMPMapping' }
    CreateLink:
      type: object
      required: [kind]
      properties:
        kind: { type: string, enum: [property, ump] }
        property: { $ref: '#/components/schemas/PropertyLink' }
        ump: { $ref: '#/components/schemas/UMPMapping' }
    SuggestedLink:
      type: object
      required: [link, reason]
      properties:
        link: { $ref: '#/components/schemas/CreateLink' }
        reason: { type: string }
        confidence: { type: number }
    Note:
      type: object
      required: [id, text, x, y]
      properties:
        id: { type: string }
        text: { type: string }
        x: { type: integer }
        y: { type: integer }
    GraphDoc:
      type: object
      required: [canvas, instruments, links]
      properties:
        canvas:
          type: object
          required: [width, height, theme, grid]
          properties:
            width: { type: integer }
            height: { type: integer }
            theme: { type: string, enum: [light, dark] }
            grid: { type: integer }
        instruments: { type: array, items: { $ref: '#/components/schemas/Instrument' } }
        links: { type: array, items: { $ref: '#/components/schemas/Link' } }
        notes: { type: array, items: { $ref: '#/components/schemas/Note' } }
    DiscoveredEndpoint:
      type: object
      required: [id, identity, propertySchema]
      properties:
        id: { type: string }
        identity: { $ref: '#/components/schemas/InstrumentIdentity' }
        propertySchema: { $ref: '#/components/schemas/PropertySchema' }
    StoredGraph:
      type: object
      required: [id, doc]
      properties:
        id: { type: string }
        doc: { $ref: '#/components/schemas/GraphDoc' }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
        etag: { type: string }
    VendorIdentity:
      type: object
      properties:
        manufacturerId: { type: string }
        familyCode: { type: integer }
        modelCode: { type: integer }
        revision: { type: integer }
        subtreeStrategy: { type: string, enum: [sequential, hash-instanceId] }
    Allocation:
      type: object
      required: [instrumentId, subId]
      properties:
        instrumentId: { type: string }
        subId: { type: integer }
        issuedAt: { type: string, format: date-time }
    CorpusSnapshot:
      type: object
      properties:
        version: { type: integer }
        instruments: { type: array, items: { $ref: '#/components/schemas/Instrument' } }
        links: { type: array, items: { $ref: '#/components/schemas/Link' } }
        vendorIdentity: { $ref: '#/components/schemas/VendorIdentity' }
        notes: { type: array, items: { $ref: '#/components/schemas/Note' } }
