generate:
  - types
  - server
accessModifier: public
filter:
  paths:
    - /capabilities
    - /corpora
    - /corpora/{corpusId}/baselines
    - /corpora/{corpusId}/reflections
    - /corpora/{corpusId}/functions
    - /corpora/{corpusId}/analyses
    - /functions
    - /functions/{functionId}
