openapi: 3.1.0
info:
  title: PatchBay Service API (client copy)
  version: 1.0.0
servers:
  - url: http://localhost:7090
paths:
  /health:
    get:
      operationId: getHealth
      responses:
        '200': { description: OK, content: { application/json: { schema: { type: object, properties: { status: { type: string } } } } } }
  /instruments:
    get:
      operationId: listInstruments
      responses: { '200': { description: Instruments, content: { application/json: { schema: { type: array, items: { $ref: '#/components/schemas/Instrument' } } } } } }
  /graph/suggest:
    post:
      operationId: suggestLinks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nodeIds: { type: array, items: { type: string } }
                includeUMP: { type: boolean, default: true }
      responses:
        '200': { description: Suggestions, content: { application/json: { schema: { type: array, items: { $ref: '#/components/schemas/SuggestedLink' } } } } }
  /links:
    get:
      operationId: listLinks
      responses:
        '200':
          description: Links
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Link' }
    post:
      operationId: createLink
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateLink' }
      responses:
        '201': { description: Created, content: { application/json: { schema: { $ref: '#/components/schemas/Link' } } } }
  /links/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    delete:
      operationId: deleteLink
      responses:
        '204': { description: Deleted }
  /store/graphs:
    get:
      operationId: listStoredGraphs
      responses:
        '200':
          description: Stored graphs
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/StoredGraph' }
  /store/graphs/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }
    get:
      operationId: getStoredGraph
      responses:
        '200': { description: Stored Graph, content: { application/json: { schema: { $ref: '#/components/schemas/StoredGraph' } } } }
    put:
      operationId: putStoredGraph
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/StoredGraph' }
      responses:
        '204': { description: Upserted }
  /admin/vendor-identity:
    get:
      operationId: getVendorIdentity
      responses:
        '200': { description: Identity, content: { application/json: { schema: { $ref: '#/components/schemas/VendorIdentity' } } } }
    put:
      operationId: putVendorIdentity
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/VendorIdentity' } } }
      responses: { '204': { description: Updated } }
  /corpus/snapshot:
    post:
      operationId: createCorpusSnapshot
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                includeSchemas: { type: boolean }
                includeMappings: { type: boolean }
      responses:
        '200': { description: Snapshot, content: { application/json: { schema: { $ref: '#/components/schemas/CorpusSnapshot' } } } }
components:
  schemas:
    InstrumentKind:
      type: string
      enum: [mvk.triangle, mvk.quad, external.coremidi]
    InstrumentIdentity:
      type: object
      properties:
        manufacturer: { type: string }
        product: { type: string }
        displayName: { type: string }
        instanceId: { type: string }
        muid28: { type: integer }
        hasUMPInput: { type: boolean }
        hasUMPOutput: { type: boolean }
    PropertySchema:
      type: object
      required: [version, properties]
      properties:
        version: { type: integer }
        properties:
          type: array
          items:
            type: object
            required: [name, type]
            properties:
              name: { type: string }
              type: { type: string, enum: [float, int, bool, string, enum] }
              min: { type: number }
              max: { type: number }
              step: { type: number }
              default: { oneOf: [ { type: number }, { type: integer }, { type: boolean }, { type: string } ] }
              enumValues: { type: array, items: { type: string } }
              aliases: { type: array, items: { type: string } }
    Instrument:
      type: object
      required: [id, kind, x, y, w, h, identity, propertySchema]
      properties:
        id: { type: string }
        kind: { $ref: '#/components/schemas/InstrumentKind' }
        title: { type: string }
        x: { type: integer }
        y: { type: integer }
        w: { type: integer }
        h: { type: integer }
        identity: { $ref: '#/components/schemas/InstrumentIdentity' }
        propertySchema: { $ref: '#/components/schemas/PropertySchema' }
        propertyDefaults: { type: object, additionalProperties: { oneOf: [ { type: number }, { type: integer }, { type: boolean }, { type: string } ] } }
    GraphDoc:
      type: object
      required: [canvas, instruments, links]
      properties:
        canvas:
          type: object
          required: [width, height, theme, grid]
          properties:
            width: { type: integer }
            height: { type: integer }
            theme: { type: string, enum: [light, dark] }
            grid: { type: integer }
        instruments: { type: array, items: { $ref: '#/components/schemas/Instrument' } }
        links: { type: array, items: { $ref: '#/components/schemas/Link' } }
    StoredGraph:
      type: object
      required: [id, doc]
      properties:
        id: { type: string }
        doc: { $ref: '#/components/schemas/GraphDoc' }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
        etag: { type: string }
    PropertyRef:
      type: string
    PropertyLink:
      type: object
      properties:
        from: { $ref: '#/components/schemas/PropertyRef' }
        to: { $ref: '#/components/schemas/PropertyRef' }
        direction: { type: string, enum: [a_to_b, b_to_a, bidirectional] }
    SuggestedLink:
      type: object
      required: [link, reason]
      properties:
        link: { $ref: '#/components/schemas/CreateLink' }
        reason: { type: string }
        confidence: { type: number }
    UMPMessageKind:
      type: string
      enum: [noteOn, noteOff, cc, pitchBend]
    UMPSource:
      type: object
      required: [endpointId, group, channel, message]
      properties:
        endpointId: { type: string }
        group: { type: integer }
        channel: { type: integer }
        message: { $ref: '#/components/schemas/UMPMessageKind' }
        cc: { type: integer }
        note: { type: integer }
    MappingFunction:
      type: object
      properties:
        scale: { type: number }
        offset: { type: number }
        outMin: { type: number }
        outMax: { type: number }
        smoothing: { type: number }
        curve: { type: string, enum: [linear, exp, log] }
    UMPMapping:
      type: object
      required: [source, to]
      properties:
        source: { $ref: '#/components/schemas/UMPSource' }
        to: { $ref: '#/components/schemas/PropertyRef' }
        map: { $ref: '#/components/schemas/MappingFunction' }
    Link:
      type: object
      required: [id, kind]
      properties:
        id: { type: string }
        kind: { type: string, enum: [property, ump] }
        property: { $ref: '#/components/schemas/PropertyLink' }
        ump: { $ref: '#/components/schemas/UMPMapping' }
    CreateLink:
      type: object
      required: [kind]
      properties:
        kind: { type: string, enum: [property, ump] }
        property: { $ref: '#/components/schemas/PropertyLink' }
        ump: { $ref: '#/components/schemas/UMPMapping' }
    VendorIdentity:
      type: object
      properties:
        manufacturerId: { type: string }
        familyCode: { type: integer }
        modelCode: { type: integer }
        revision: { type: integer }
        subtreeStrategy: { type: string, enum: [sequential, hash-instanceId] }
    CorpusSnapshot:
      type: object
      properties:
        version: { type: integer }
        instruments: { type: array, items: { $ref: '#/components/schemas/Instrument' } }
        links: { type: array, items: { $ref: '#/components/schemas/Link' } }
