openapi: 3.1.0
info:
  title: FountainAI Auth Gateway Plugin
  description: >
    Lightweight authentication gateway plugin exposing token validation
    and claims retrieval endpoints.
  version: 1.0.0
  x-fountain.port: 8010
  x-fountain.binary: fountain-gateway
  license:
    name: FountainAI Internal
    url: https://fountain.coach/licenses/internal
x-persona: ../personas/auth.md
servers:
  - url: http://gateway.local
    description: Local development
  - url: http://gateway.fountain.coach
security:
  - BearerAuth: []
paths:
  /auth/validate:
    post:
      summary: Validate Access Token
      description: Verifies a bearer token and returns its role when valid.
      operationId: authValidate
      x-fountain.visibility: public
      x-fountain.reason: ''
      x-fountain.allow-as-tool: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRequest'
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Token is invalid or expired
  /auth/claims:
    get:
      summary: Retrieve Claims
      description: Returns claims associated with the supplied bearer token.
      operationId: authClaims
      x-fountain.visibility: public
      x-fountain.reason: ''
      x-fountain.allow-as-tool: true
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            description: Bearer access token
      responses:
        '200':
          description: Claims found for token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Token is missing or invalid
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    BadRequest:
      description: Malformed request payload.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required: [error]
  schemas:
    ValidateRequest:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    ValidationResponse:
      type: object
      properties:
        valid:
          type: boolean
        role:
          oneOf:
            - type: string
            - type: 'null'
      required:
        - valid
    ClaimsResponse:
      type: object
      properties:
        role:
          oneOf:
            - type: string
            - type: 'null'
        scopes:
          type: array
          items:
            type: string
      required:
        - scopes

# © 2025 Contexter alias Benedikt Eickhoff 🛡️ All rights reserved.
