openapi: 3.1.0
info:
  title: Teatro Input Service
  version: 0.1.0
  summary: Logical input actions, devices, and bindings for the Teatro Game Engine.
  description: |
    The Teatro Input Service describes how raw input (keyboard keys, mouse movement,
    gamepad buttons/axes, MIDI events, etc.) is mapped into high-level "actions"
    that game code can use (for example "jump", "moveForward", "fire").

    This spec is written as documentation for humans and LLMs and focuses on the
    mental model of engine input:

    - InputDevice: a physical or virtual device that produces input signals. Examples
      include keyboards, mice, gamepads, MIDI controllers, or touch screens.
    - Action: a named, high-level intent in the game (for example "jump" or
      "openMenu"). Actions are the primary API that game logic uses.
    - Binding: a mapping between device signals (keys, buttons, axes, MIDI notes)
      and actions. Bindings define how players control actions across different
      devices.
    - ActionState: the current value of an action (for example pressed, held, or
      an analog value between -1 and 1).

    The Input Service is designed to work alongside the Teatro Game Engine Core:
    core entities and scripts refer to actions by name, while this service
    describes how those actions are driven by one or more devices.
  license:
    name: FountainAI Internal
    url: https://fountain.coach/internal
servers:
  - url: http://127.0.0.1:0
    description: Logical Teatro Input host (embedded or via Tools Factory)

tags:
  - name: actions
    description: Define and inspect high-level input actions.
  - name: devices
    description: Describe input devices and their capabilities.
  - name: bindings
    description: Map device signals to actions.
  - name: state
    description: Feed raw input events and query current action state.

paths:
  /sessions/{sessionId}/input/actions:
    parameters:
      - $ref: '#/components/parameters/SessionId'
    get:
      tags: [actions]
      operationId: teatro.input.listActions
      summary: List input actions for a session
      description: |
        Returns all input actions defined for the given game session. Each
        action describes its semantic meaning (for example "jump") and value
        type (button or analog).
      x-fountain.visibility: public
      x-fountain.reason: inspect high-level input actions defined for a session
      x-fountain.allow-as-tool: true
      security: []
      responses:
        '200':
          description: List of input actions
          content:
            application/json:
              schema:
                type: object
                properties:
                  actions:
                    type: array
                    items:
                      $ref: '#/components/schemas/InputAction'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags: [actions]
      operationId: teatro.input.createAction
      summary: Create or upsert an input action
      description: |
        Creates a new input action or updates an existing one. Actions are
        referenced by name in game logic and in bindings.
      x-fountain.visibility: public
      x-fountain.reason: define or update logical input action (e.g. \"jump\")
      x-fountain.allow-as-tool: true
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputAction'
      responses:
        '200':
          description: Created or updated action
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InputAction'
        '400':
          description: Invalid action definition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /sessions/{sessionId}/input/devices:
    parameters:
      - $ref: '#/components/parameters/SessionId'
    get:
      tags: [devices]
      operationId: teatro.input.listDevices
      summary: List input devices
      description: |
        Returns all input devices registered for the session. Devices describe
        their type (keyboard, gamepad, etc.) and identifiers.
      x-fountain.visibility: public
      x-fountain.reason: inspect which physical or virtual devices are known
      x-fountain.allow-as-tool: true
      security: []
      responses:
        '200':
          description: List of input devices
          content:
            application/json:
              schema:
                type: object
                properties:
                  devices:
                    type: array
                    items:
                      $ref: '#/components/schemas/InputDevice'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags: [devices]
      operationId: teatro.input.registerDevice
      summary: Register or update an input device
      description: |
        Registers a device and its metadata. In many cases, devices are
        auto-detected by the engine, but tools and tests may also register
        virtual devices explicitly.
      x-fountain.visibility: public
      x-fountain.reason: register or update metadata for an input device
      x-fountain.allow-as-tool: true
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDevice'
      responses:
        '200':
          description: Device registered or updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InputDevice'
        '400':
          description: Invalid device definition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /sessions/{sessionId}/input/bindings:
    parameters:
      - $ref: '#/components/parameters/SessionId'
    get:
      tags: [bindings]
      operationId: teatro.input.listBindings
      summary: List action bindings
      description: |
        Returns all bindings for the session. A binding maps device inputs
        (for example a key or button) to a named action.
      x-fountain.visibility: public
      x-fountain.reason: inspect how actions are bound to devices
      x-fountain.allow-as-tool: true
      security: []
      responses:
        '200':
          description: List of bindings
          content:
            application/json:
              schema:
                type: object
                properties:
                  bindings:
                    type: array
                    items:
                      $ref: '#/components/schemas/ActionBinding'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags: [bindings]
      operationId: teatro.input.setBindings
      summary: Replace or merge bindings
      description: |
        Replaces or merges action bindings for the session. This endpoint is
        typically used by tools or in-game menus to rebind controls.
      x-fountain.visibility: public
      x-fountain.reason: update mapping from device inputs to actions
      x-fountain.allow-as-tool: true
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mode:
                  type: string
                  description: Whether to replace all existing bindings or merge.
                  enum: [replace, merge]
                  default: merge
                bindings:
                  type: array
                  items:
                    $ref: '#/components/schemas/ActionBinding'
      responses:
        '200':
          description: Updated bindings
          content:
            application/json:
              schema:
                type: object
                properties:
                  bindings:
                    type: array
                    items:
                      $ref: '#/components/schemas/ActionBinding'
        '400':
          description: Invalid bindings payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /sessions/{sessionId}/input/events:
    parameters:
      - $ref: '#/components/parameters/SessionId'
    post:
      tags: [state]
      operationId: teatro.input.injectEvents
      summary: Inject raw input events
      description: |
        Injects a batch of raw input events into the session. The engine
        updates action states based on current bindings and device metadata.
        This endpoint is primarily used by tests, tools, or remote controllers.
      x-fountain.visibility: public
      x-fountain.reason: feed synthetic or recorded input events into the engine
      x-fountain.allow-as-tool: true
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                events:
                  type: array
                  items:
                    $ref: '#/components/schemas/InputEvent'
      responses:
        '202':
          description: Events accepted and queued for processing
        '400':
          description: Invalid events payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /sessions/{sessionId}/input/state:
    parameters:
      - $ref: '#/components/parameters/SessionId'
    get:
      tags: [state]
      operationId: teatro.input.getActionState
      summary: Get current action state
      description: |
        Returns the current value of one or more actions (for example whether
        "jump" is pressed or the current analog value of "moveForward") at the
        time of the query.
      x-fountain.visibility: public
      x-fountain.reason: query high-level action state for a session
      x-fountain.allow-as-tool: true
      security: []
      parameters:
        - name: actions
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
          description: Optional list of action names to filter by.
      responses:
        '200':
          description: Current action state
          content:
            application/json:
              schema:
                type: object
                properties:
                  actions:
                    type: array
                    items:
                      $ref: '#/components/schemas/ActionState'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    SessionId:
      name: sessionId
      in: path
      required: true
      schema:
        type: string
      description: Identifier of the game session this input state belongs to.

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    InputValueType:
      type: string
      description: |
        Describes how an action's value should be interpreted.
        - button: on/off or pressed/held.
        - axis1D: one-dimensional analog axis (for example -1 to 1).
      enum:
        - button
        - axis1D

    InputAction:
      type: object
      description: |
        High-level input action used by game logic. Actions are identified
        by name and have a value type (button or analog).
      required:
        - name
        - valueType
      properties:
        name:
          type: string
          description: Unique name for this action (for example \"jump\").
        valueType:
          $ref: '#/components/schemas/InputValueType'
        description:
          type: string
          description: Human-readable description of what this action does.

    InputDeviceType:
      type: string
      description: |
        Type of input device. This is intentionally coarse and focuses on
        semantics rather than hardware details.
      enum:
        - keyboard
        - mouse
        - gamepad
        - midi
        - touch
        - other

    InputDevice:
      type: object
      description: |
        Represents an input device that can produce events. Devices may
        map to physical hardware or virtual/test sources.
      required:
        - id
        - type
      properties:
        id:
          type: string
          description: Unique identifier of the device within a session.
        type:
          $ref: '#/components/schemas/InputDeviceType'
        displayName:
          type: string
          description: Optional human-readable name (for example \"Xbox Controller\").
        vendorId:
          type: string
          description: Optional vendor identification string.
        productId:
          type: string
          description: Optional product identification string.

    DeviceSignal:
      type: object
      description: |
        A specific signal on a device that can drive an action. Examples:
        keyboard key, gamepad button, axis, or MIDI note/control.
      required:
        - deviceId
        - kind
      properties:
        deviceId:
          type: string
          description: Identifier of the device that emits this signal.
        kind:
          type: string
          description: Type of signal on the device.
          enum:
            - keyboardKey
            - mouseButton
            - mouseAxis
            - gamepadButton
            - gamepadAxis
            - midiNote
            - midiCC
            - other
        code:
          type: string
          description: |
            Implementation-specific code for the signal (for example key code,
            button index, axis name, or MIDI note/CC number).

    ActionBinding:
      type: object
      description: |
        Maps a device signal to an action, optionally with scaling, deadzones,
        or inversion for analog inputs.
      required:
        - actionName
        - signal
      properties:
        actionName:
          type: string
          description: Name of the action this binding drives.
        signal:
          $ref: '#/components/schemas/DeviceSignal'
        scale:
          type: number
          format: float
          description: Optional scale factor for analog signals.
        deadzone:
          type: number
          format: float
          description: Optional deadzone for analog signals (0 to 1).
        invert:
          type: boolean
          description: Whether to invert the analog value.

    InputEvent:
      type: object
      description: |
        Raw input event from a device. The engine interprets events according
        to the device type and current bindings.
      required:
        - deviceId
        - kind
        - timestampMs
      properties:
        deviceId:
          type: string
        kind:
          type: string
          description: |
            Event kind, aligned loosely with DeviceSignal kinds but including
            additional context (for example keyDown/keyUp).
          enum:
            - keyDown
            - keyUp
            - buttonDown
            - buttonUp
            - axisMotion
            - midiNoteOn
            - midiNoteOff
            - midiCC
            - other
        code:
          type: string
          description: Signal code (for example key code or button index).
        value:
          type: number
          format: float
          description: |
            Optional analog value for the event (for example axis position or
            MIDI velocity). Button-style events may omit this.
        timestampMs:
          type: number
          format: float
          description: Event timestamp in milliseconds (session-local or monotonic).

    ActionState:
      type: object
      description: |
        Represents the current state of an action at query time. For buttons,
        the value is typically 0 or 1. For analog actions, the value is in a
        continuous range (for example -1 to 1).
      required:
        - actionName
        - value
      properties:
        actionName:
          type: string
        value:
          type: number
          format: float
          description: Current numeric value of the action.
        isActive:
          type: boolean
          description: Convenience flag indicating whether the action is considered "on".

    ErrorResponse:
      type: object
      description: Standard error response with human-readable message.
      properties:
        code:
          type: string
        message:
          type: string

