openapi: 3.1.0
info:
  title: FountainAI Tools Factory Service
  description: |
    Service that registers new tools (function definitions) and stores
    them in the shared FountainStore corpus used by the Function Caller
    Service.
  version: 1.0.0
  x-fountain.port: 8011
  x-fountain.binary: tools-factory
  license:
    name: FountainAI Internal
servers:
  - url: http://tools-factory.local
    description: Local development
  - url: http://tools-factory.fountain.coach
security: []
paths:
  /tools:
    get:
      summary: List Registered Tools
      operationId: list_tools
      x-fountain.visibility: public
      x-fountain.reason: ''
      x-fountain.allow-as-tool: true
      description: Retrieve a paginated list of registered tools.
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          description: Number of tools per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionListResponse'
        '422':
          $ref: '#/components/responses/ValidationErrorResponse'

  /tools/register:
    post:
      summary: Register Tools from OpenAPI
      operationId: register_openapi
      x-fountain.visibility: public
      x-fountain.reason: ''
      x-fountain.allow-as-tool: true
      description: |
        Store a collection of tool definitions provided via an OpenAPI
        document. Each operationId is mapped to a callable function.
      parameters:
        - name: corpusId
          in: query
          description: Corpus identifier to associate the tools with
          schema:
            type: string
            default: default
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenAPIDocument'
      responses:
        '200':
          description: Tools registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionListResponse'
        '422':
          $ref: '#/components/responses/ValidationErrorResponse'

  /agent-facts/from-openapi:
    post:
      summary: Generate and optionally seed agent facts from OpenAPI
      operationId: agentFacts_fromOpenAPI
      x-fountain.visibility: public
      x-fountain.reason: ''
      x-fountain.allow-as-tool: true
      description: |
        Generate Property Exchange facts for an agent from an OpenAPI document and,
        when requested, seed them into FountainStore under the `agents` corpus.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentFactsFromOpenAPIRequest'
      responses:
        '200':
          description: Generated facts (and seeded when requested)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentFactsResponse'
        '400':
          description: Invalid request (missing agentId or OpenAPI payload)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Generator or IO failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /agent-facts:
    get:
      summary: Fetch stored agent facts
      operationId: agentFacts_get
      x-fountain.visibility: public
      x-fountain.reason: ''
      x-fountain.allow-as-tool: true
      description: |
        Return the stored facts document for a given agentId from FountainStore.
      parameters:
        - name: agentId
          in: query
          required: true
          description: Agent identifier (e.g. fountain.coach/agent/infinity/service)
          schema:
            type: string
        - name: corpusId
          in: query
          required: false
          description: Corpus containing the facts document (defaults to agents).
          schema:
            type: string
            default: agents
      responses:
        '200':
          description: Stored facts document
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid request (missing agentId)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Facts not found for the given agentId/corpus
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      x-fountain.visibility: public
      x-fountain.reason: ''
      x-fountain.allow-as-tool: true
      responses:
        '200':
          description: Successful Response
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request
components:
  schemas:
    FunctionInfo:
      type: object
      required:
        - function_id
        - name
        - description
        - http_method
        - http_path
      properties:
        function_id:
          type: string
          description: Unique function identifier (matches operationId)
        name:
          type: string
          description: Human-readable name of the function
        description:
          type: string
          description: Description of the function's purpose
        http_method:
          type: string
          enum: [GET, POST, PUT, PATCH, DELETE]
          description: HTTP method used to invoke the function
        http_path:
          type: string
          description: HTTP path to call for the function
        parameters_schema:
          type: object
          description: JSON Schema describing input parameters for validation
        openapi:
          type: object
          description: Full OpenAPI document defining the tool
    FunctionListResponse:
      type: object
      properties:
        functions:
          type: array
          items:
            $ref: '#/components/schemas/FunctionInfo'
        page:
          type: integer
        page_size:
          type: integer
        total:
          type: integer
    OpenAPIDocument:
      description: OpenAPI specification describing one or more tools
      type: object
      additionalProperties: true
    AgentFactsFromOpenAPIRequest:
      type: object
      description: Request to generate (and optionally seed) agent facts from an OpenAPI spec.
      required:
        - agentId
      properties:
        agentId:
          type: string
          description: Agent identifier (e.g. fountain.coach/agent/infinity/service).
        corpusId:
          type: string
          description: Corpus id to write facts into when seeding.
          default: agents
        seed:
          type: boolean
          description: When true, write facts into FountainStore as well as returning them.
          default: true
        openapi:
          description: Inline OpenAPI document to use as the source of truth.
          allOf:
            - $ref: '#/components/schemas/OpenAPIDocument'
        specURL:
          type: string
          format: uri
          description: URL pointing at an OpenAPI document (alternative to inline `openapi`).
    AgentFactsResponse:
      type: object
      description: Response containing generated facts and seeding metadata.
      required:
        - agentId
        - corpusId
        - facts
      properties:
        agentId:
          type: string
        corpusId:
          type: string
        seeded:
          type: boolean
          description: Indicates whether the facts were written into FountainStore.
        id:
          type: string
          description: Document id used when seeding into FountainStore.
        facts:
          type: object
          description: Generated facts JSON for the agent.
    ErrorResponse:
      type: object
      required:
        - error_code
        - message
      properties:
        error_code:
          type: string
          description: Machine-readable error code
        message:
          type: string
          description: Human-readable error message

  responses:
    ValidationErrorResponse:
      description: Validation error in input parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            validation_error:
              value:
                error_code: validation_error
                message: Invalid input parameters

# © 2025 Contexter alias Benedikt Eickhoff 🛡️ All rights reserved.

# © 2025 Contexter alias Benedikt Eickhoff 🛡️ All rights reserved.
